version: "3.7"
services:

  web:
    image: interview-planner
    build: webapp/.
    ports:
      - "5050:5000"

  osrm_backend:
    image: osrm-backend
    build: 
      context: osrm/.
      args:
        map_url: https://download.geofabrik.de/north-america/us/district-of-columbia-latest.osm.pbf
    ports:
      - "5000:5000"

  osrm_frontend:
    image: osrm/osrm-frontend
    ports:
      - "9966:9966"

