version: "3.7"
services:

  web:
    image: interview-planner
    build: webapp/.

  osrm_backend:
    image: osrm-backend
    build: osrm/.

  osrm_frontend:
    image: osrm/osrm-frontend
    environment:
      - OSRM_BACKEND=/osrm

  nginx:
    image: nginx:1.17
    ports:
      - "80:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"

